### ISSUE TITLE
Upgrade plans for digikam 7.3

### ISSUE THREAD

**Issue by zzatihz1** [r-pufky/digikam#10]
I installed digikam 7.3 locally on my Mac and now would like to run it in Docker on my QNAP NAS. I was hoping to migrate the database but this image version 7.2 does not recognize the newer 7.3 database. Is there a workaround or a simple way to enable this 7.2 version to use the 7.3 database?

Thanks in advance.

**Comment by r-pufky** [comment]
I'm currently traveling but will look into it when I go to update the
containers with bullseye this weekend. Usually the db migrations are
handled automatically with the digital version bumps.

**Comment by zzatihz1** [comment]
Safe travels . . . Thank you for the quick response. I'll keep my eyes out for the update. Again, many thanks!

**Comment by r-pufky** [comment]
I just built the new container and my installation of 7.2.0 migrated correctly to 7.3.0. I'd suggested installing the 7.3.0 version on your QNAP and go from there.

Note: if you are using a personally installed version of digikam and moving to a dockerized version, it's likely that all of your file paths are different unless you specifically account for this. This is outside the scope of the docker image.

> Is there a workaround or a simple way to enable this 7.2 version to use the 7.3 database?

No, there were a bunch of database related changes in the ~370 patches for the 7.3.0 release. [see release notes here](https://www.digikam.org/news/2021-07-12-7.3.0_release_announcement/) Using the latest release (7.3.0) should work fine however.

**Comment by zzatihz1** [comment]
THANK YOU! The upgrade worked perfectly.

I take it from your note regarding file paths that multiple instances of DK to the same DB may not work properly if the file paths are from different shares. Makes sense.

**Comment by r-pufky** [comment]
> I take it from your note regarding file paths that multiple instances of DK to the same DB may not work properly if the file paths are from different shares. Makes sense.

Correct. Digikam is designed as a single user application, so you can do some tricks to run multiple instances on one backend, but I'd recommend against it. here be dragons.
