### ISSUE TITLE
Exiftool?

### ISSUE THREAD

**Issue by zzatihz1** [r-pufky/digikam#11]
It looks like DK 7.3 now supports the Exiftool. However, DK does not find it in this image and it looks like when you try to install it, it can't. Is this something you could address as part of your image?

Many thanks in advance! Your work is greatly appreciated.

**Comment by r-pufky** [comment]
Thanks for the report --

I've included exiftool in the new latest image. Can you run that and verify that it is working as expected?

rpufky/digikam:latest

**Comment by zzatihz1** [comment]
YES! DK now acknowledges exiftool presence.

At first I didn't think it did but I realized I was still using the stable image. Once I changed the tag to latest and recreated the container, it did work. 

Thanks again for the quick response!

**Comment by r-pufky** [comment]
No worries -- I created a fix in latest for you to test. I just pushed that fix to the other releases, so you should be able to go back to stable without any issues.

Thanks for the report!
