### ISSUE TITLE
Export (SmugMug) not working

### ISSUE THREAD

**Issue by zzatihz1** [r-pufky/digikam#12]
Should DK export work in this container?

I have a SmugMug account and wanted to export to SmugMug but did not see anywhere to setup my account. I tried on my Mac install of DK and it looks like when you initiate a SmugMug export, it launches a browser for you to authenticate to your account which then likely establishes an authorized link between DK and SmugMug.

I will try setting up a DK link to SmugMug on my Mac and see if it transfers to my Docker install. I don't see how it would since DK installs are independent.

I have not checked other export services since that is not my use case. Perhaps other users of you image can validate other export services.

**Comment by r-pufky** [comment]
@zzatihz1  -- I just pushed an updated image a minute or two ago; can you confirm your issue is still the case after updating?

> It launches a browser for you to authenticate to your account which then likely establishes an authorized link between DK and SmugMug.

Another case like this was handled with tag metadata; try minimizing the digikam app within the interface and see if it popped behind. If not, and it really requires a browser install for configuration we can figure out what needs to be done to make it work.

> I will try setting up a DK link to SmugMug on my Mac and see if it transfers to my Docker install. I don't see how it would since DK installs are independent.

As for the container, this should be fully functional as per the installed application; so importing the settings with a equivalent version should work, though I'd rather fix the issue within the container itself.

> I have not checked other export services since that is not my use case. Perhaps other users of you image can validate other export services.

Yup -- I've been fixing issues as they have been reported; I suspect a majority of the usage is photo management, not necessarily exporting.

**Comment by zzatihz1** [comment]
> Another case like this was handled with tag metadata; try minimizing the digikam app within the interface and see if it popped behind. If not, and it really requires a browser install for configuration we can figure out what needs to be done to make it work.

I downloaded the latest image and it did not make a difference. I also checked for any popups behind the app and there weren't any for SmugMug. I also tried with a VNC connection and had similar results.

I then tried to export to OneDrive just to see the behavior and I did see a popup asking me to authenticate my OneDrive account. I'm not sure what's different between the SmugMug and OneDriver exporter.

**Comment by r-pufky** [comment]
Thanks for the info. I'll look into getting it fixed shortly. Outside of what you posted above, are there any additional things that I should / need to know about the smugmug export process?

Otherwise except bug updates tracking progress.

**Comment by zzatihz1** [comment]
I don't believe so. Based on my local DK install on my Mac, it looks like what should happen is as follows:

- Select images to export
- Select Export to SmugMug
- The resulting dialog expects valid account information for SmugMug. Since it doesn't exit, select cancel and choose "Change Account" in the dialog box.
- From there, a browser window opens up with a SmugMug URL prompting me to enter my SmugMug credentials. I'm assuming this will authorize SmugMug to accept DK connections via their API.
- After authenticating on the SmugMug site, you provide authorization to the DK api and SmugMug then returns a URL with localhost and keys. This then fails in my situation since I have DK running locally on my Mac. Maybe there are more issues with the SmugMug plugin as well.

This is not critical to me but it would really help my workflow in uploading photos to SmugMug. I have other tools to accomplish this but being able to do this directly from DK would be very helpful.

**Comment by r-pufky** [comment]
Pull the 'latest' image. I've updated the image and have testing linking with a free acount (no option to sell photos). See attached  image from smugmug account:

![digikam-authorization](https://user-images.githubusercontent.com/4778046/133178316-fd0f16c0-ad7c-4e5a-832d-264e6f5826ea.png)

Let me know if this works for you.

**Comment by zzatihz1** [comment]
I just had time for a quick test and it looks like it works. I am not 100% sure and will do more tests tomorrow.

Initially after establishing the connection, the export did not work. I exited the process and decided to test an import and that did work. Then I tested an export again and it seemed to work. 

I will do more extensive testing tomorrow and confirm with you by end of day. 

Thank you so much for the prompt responses and I promise to get back to you within 24 hours!

**Comment by zzatihz1** [comment]
I've done further testing and I would say the issue is closed.

There are some interesting nuances in how the SmugMug plugin works but that has nothing do with your implementation in the container. I can confirm that the creation of folders and exporting to these folders is working from DK as intended.

Thank you again for the quick response!

**Comment by r-pufky** [comment]
No worries. Thanks for confirming that it works. I'll update the base image shortly.

**Comment by r-pufky** [comment]
Stable image now has the fix applied. closing.
