### ISSUE TITLE
Digikam 7.7.0

### ISSUE THREAD

**Issue by sse450** [r-pufky/digikam#16]
Dear r-pufky,

would you please so kind to update digikam to 7.7.0?
I appreciate your efforts for bringing us such a nice docker.
Thanks.

**Comment by r-pufky** [comment]
I'll update the final docker image by this weekend -- please note, after 7.7 this image will be unsupported, and you should look to the linuxserver digikam image (I've worked with those folks to make migrations as painless as possible).

https://hub.docker.com/r/linuxserver/digikam

**Comment by sse450** [comment]
I am sad hearing about your decision. Anyway, I  respect it.

In the past, I tried linuxserver image. As their image doesn't have LANG,  LANGUAGE and LC_ALL environment variables, non-english characters are not visible. I had informed them but no solution so far.

Thank you for all your efforts for this image. 

Best regards

**Comment by r-pufky** [comment]
Thanks -- I appreciate it.

I've updated the docker images and are pushing 7.7.0 now; should be available in the next few minutes. The last image update will be the 8.0.0 release of digikam.

You can always clone this repository and maintain the image yourself after it's discontinued.

**Comment by r-pufky** [comment]
Resolving issue. 7.7.0 is now live.
