### ISSUE TITLE
Update base image?

### ISSUE THREAD

**Issue by stumpylog** [r-pufky/digikam#7]
Hello - 

Would it be possible to update the base image to debain-10?  There's a `jlesage/baseimage-gui:debian-10`  out for a few months now, so I figure it's probably stable.  I was able to build it locally with the `make stable_no_gpg` target.

**Comment by r-pufky** [comment]
I will update and kickoff a new build tonight.

**Comment by r-pufky** [comment]
New images are pushed, and I've updated the GPG validation to use an explicit default server.
