### ISSUE TITLE
Web UI will not open on Digikam 7.2.0

### ISSUE THREAD

**Issue by sse450** [r-pufky/digikam#8]
Upgraded from 7.1.0 to 7.2.0.

All I get is a black area in the placeholder for digikam.

Two problems in logs:
1. Update-locale: Unable to write /etc/default/locale: Permission denied
2. libgssapi_krb5.so.2: No such file or directory

```
[app] starting Digikam 7.2.0...
update-locale: Unable to write /etc/default/locale: Permission denied
-- digiKam Linux AppImage Bundle
-- Use 'help' as CLI argument to know all available options for digiKam application.
-- Notes: to integrate this bundle to your desktop, use AppImageLauncher.
-- to enable all debug messages on the console, use 'export QT_LOGGING_RULES="digikam*=true"'.
libudev.so.0
libxcb-dri3.so.0
-- Preloading shared libs: :/usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0
digikam: error while loading shared libraries: libgssapi_krb5.so.2: cannot open shared object file: No such file or directory
```

**Comment by r-pufky** [comment]
I'll take a look in the morning - can you provide your docker config? Think I know what is going on.

**Comment by r-pufky** [comment]
Taking a look now.

**Comment by r-pufky** [comment]
Two issues:

* There's a dependency update that is required for facial recognition
* https://bugs.kde.org/show_bug.cgi?id=435065#c8 -- if you are using a DB backend, stored functions are now used with facial recognition, this requires superuser (root) DB rights, or enabling it for that DB.

I've just built a new container and explicitly tested facial recognition deps. Should work fine now -- will be pushing a new build shortly as well as updating documentation.

**Comment by r-pufky** [comment]
This has been pushed live, documentation updated.

Thanks for reporting!
