### ISSUE TITLE
Docker compose example is missing ports

### ISSUE THREAD

**Issue by Sithuk** [r-pufky/digikam#9]
The readme file contains an example docker compose. It is missing the port forwarding information needed to make a VNC connection. Suggested text below with ports and container_name configuration option.
---
version: "3"
services:
  digikam:
    image: rpufky/digikam:stable
    container_name: digikam
    ports:
      - "5900:5900"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - UMASK=022
      - TZ=America/Los_Angeles
      - KEEP_APP_RUNNING=1
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
      - ENABLE_CJK_FONT=1
    volumes:
      - /my/docker/service/config:/config
      - /my/photo/location:/data
      - /etc/localtime:/etc/localtime:ro

**Comment by r-pufky** [comment]
Hi Sithuk,

thanks for the report. Primarily the container was design with webfront usage in mind, with VNC usage as optional. This is listed in the instructions as an optional port, in the ports section:

| port | type | description
| --- | --- | --- |
| 5900 | Optional | Port used to access the application's GUI via the VNC protocol. Optional if no VNC client is used. |

This was left out of configuration examples so folks don't leave an open, unused VNC port, but had the option to turn it on if they wanted.

**Comment by Sithuk** [comment]
The example docker compose doesn't have any port forwarding section. Port 5800 is forwarded in the example docker config, but not the compose config.

**Comment by r-pufky** [comment]
Oh, gotcha -- I mis-understood what you were saying, I thought you were saying to add the VNC ports, not that the standard ports were missing from the example. Will update documentation shortly.
